stats-server:
  name: stats-server

spring:
  application:
    name: main-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:6543/main
    url: jdbc:postgresql://ewm-db:5432/main
    username: main
    password: main

#  config:
#    activate:
#      on-profile: ci,test
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:file:./db/main
#    username: main
#    password: main

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: trace
server:
  port: 0