services:



  user-db:
    image: postgres:16.1
    container_name: postgres-user-db
    ports:
      - "6544:5432"
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=users
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 10s
      retries: 15


  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 10s
      retries: 15
    networks:
      - ewm-net

  comment-db:
    image: postgres:16.1
    container_name: postgres-comment-db
    ports:
      - "6546:5432"
    environment:
      - POSTGRES_PASSWORD=comment
      - POSTGRES_USER=comment
      - POSTGRES_DB=comments
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 10s
      retries: 15
    networks:
      - ewm-net

  request-db:
    image: postgres:16.1
    container_name: postgres-request-db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_PASSWORD=request
      - POSTGRES_USER=request
      - POSTGRES_DB=requests
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 10s
      retries: 15
    networks:
      - ewm-net

  events-db:
    image: postgres:16.1
    container_name: postgres-event-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=event
      - POSTGRES_USER=event
      - POSTGRES_DB=events

#  ewm-db:
#      image: postgres:16.1
#      container_name: postgres-main-db
#      ports:
#        - "6543:5432"
#      environment:
#        - POSTGRES_PASSWORD=main
#        - POSTGRES_USER=main
#        - POSTGRES_DB=main

networks:
  ewm-net:
    driver: bridge




