kafka:
  topics:
    user-actions: stats.user-actions.v1

  producer:
    bootstrap_server: localhost:9092
    key_serialize_class: org.apache.kafka.common.serialization.StringSerializer
    value_serialize_class: kafka.serializer.AvroSerializer
    linger-ms: 0  # Отключаем задержку перед отправкой
    batch-size: 1  # Отправлять каждое сообщение отдельно
    max-in-flight-requests: 1  # По одному сообщению за раз
  consumer:
    enabled: false
server:
  port: 8081
grpc:
  server:
    port: 9090

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG
    io.grpc: DEBUG