kafka:
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

  producer:
    bootstrap_server: localhost:9092
    key_serialize_class: org.apache.kafka.common.serialization.StringSerializer
    value_serialize_class: kafka.serializer.AvroSerializer
  consumer:
    enabled: true
    bootstrap_server: localhost:9092
    group_id: aggregator-group
    client_id: aggregator-consumer
    key_deserializer_class: org.apache.kafka.common.serialization.StringDeserializer
    value_deserializer_class: kafka.deserializer.UserActionDeserializer
    auto_offset_reset: earliest
    poll_timeout: 1000
server:
  port: 0

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
    io.grpc: DEBUG