server:
  port: 0
spring:
  application:
    name: request-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6545/requests
    username: request
    password: request

grpc:
  client:
    collector:
      discovery:
        enabled: true
      serviceId: collector
      address: discovery:///collector
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
      metadata:
        port: grpc.port

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: trace