spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
          - id: user_service_route
            uri: lb://user-service
            predicates:
              - Path=/admin/users/**
          - id: request_service_route
            uri: lb://request-service
            predicates:
              - Path=/users/*/requests/**
          - id: main_service_route
            uri: lb://main-service
            predicates:
               - Path=/**
#

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO


management:
  endpoints:
    web:
      exposure:
        include: "env,health,metrics"

#для просмотра путей
