spring:
  application:
    name: analyzer
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/analyzer-db
    username: analyzer
    password: analyzer


kafka:
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

  consumer:
    bootstrap_server: localhost:9092

server:
  port: 8082
grpc:
  server:
    port: 9090

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG
    io.grpc: DEBUG