spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

#  config:
#    activate:
#      on-profile: ci,test
#    datasource:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:mem:stats
#      #url: jdbc:h2:file:./db/stat  # Альтернативная конфигурация для файловой БД
#      username: stat
#      password: stat

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/stats
    username: stat
    password: stat

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: trace

server:
  port: 0